import "react-native-url-polyfill/auto";
import React,{useEffect,useState} from "react";
import {Alert,FlatList,Image,Pressable,SafeAreaView,StyleSheet,Text,TextInput,View} from "react-native";
import * as ImagePicker from "expo-image-picker";
import {createClient} from "@supabase/supabase-js";
import {Ionicons} from "@expo/vector-icons";

const url=process.env.EXPO_PUBLIC_SUPABASE_URL||"";
const key=process.env.EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"";
const supabase=url&&key?createClient(url,key):null;
const demo=[{id:"d1",username:"NOVA",text:"Welcome to NOVA — a new world for communication and creativity.",likes:128,comments:12},{id:"d2",username:"Creator",text:"Your ideas. Your community. Your world.",likes:76,comments:8}];

export default function App(){
 const[session,setSession]=useState(null),[screen,setScreen]=useState("home"),[posts,setPosts]=useState(demo);
 const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[mode,setMode]=useState("login"),[text,setText]=useState(""),[q,setQ]=useState(""),[liked,setLiked]=useState({});
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)load()},[session]);
 async function load(){if(!supabase)return;const{data}=await supabase.from("posts").select("*").order("created_at",{ascending:false}).limit(50);if(data)setPosts(data)}
 async function auth(){if(!supabase){Alert.alert("NOVA","Supabase credentials are not connected yet.");return}if(!email||!password)return Alert.alert("NOVA","Email and password are required.");const r=mode==="login"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});if(r.error)Alert.alert("NOVA",r.error.message);else if(mode==="signup")Alert.alert("NOVA","Account created. Check your email if confirmation is enabled.")}
 async function publish(){if(!text.trim())return;if(supabase&&session){const r=await supabase.from("posts").insert({user_id:session.user.id,text:text.trim()});if(r.error)return Alert.alert("NOVA",r.error.message);load()}else setPosts([{id:String(Date.now()),username:"You",text:text.trim(),likes:0,comments:0},...posts]);setText("");setScreen("home")}
 async function pick(){const p=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!p.granted)return;const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:["images"],quality:.8});if(!r.canceled)setText("📷 "+r.assets[0].uri)}
 async function like(p){setLiked({...liked,[p.id]:!liked[p.id]});if(supabase&&session&&!String(p.id).startsWith("d")){if(liked[p.id])await supabase.from("likes").delete().eq("post_id",p.id).eq("user_id",session.user.id);else await supabase.from("likes").insert({post_id:p.id,user_id:session.user.id})}}
 if(!session)return <Auth email={email} setEmail={setEmail} password={password} setPassword={setPassword} mode={mode} setMode={setMode} submit={auth}/>;
 const data=posts.filter(p=>(p.text||"").toLowerCase().includes(q.toLowerCase()));
 return <SafeAreaView style={s.root}>
  <View style={s.header}><Text style={s.logo}>NOVA</Text><Pressable onPress={()=>setScreen("search")}><Ionicons name="search" size={24} color="#fff"/></Pressable></View>
  {screen==="search"&&<TextInput value={q} onChangeText={setQ} placeholder="Search NOVA..." placeholderTextColor="#777" style={s.input}/>}
  {screen==="create"&&<View style={s.pad}><Text style={s.title}>Create post</Text><TextInput multiline value={text} onChangeText={setText} placeholder="What's new?" placeholderTextColor="#777" style={s.big}/><View style={s.row}><Pressable onPress={pick} style={s.btn}><Text style={s.bt}>Photo</Text></Pressable><Pressable onPress={publish} style={s.primary}><Text style={s.dark}>Publish</Text></Pressable></View></View>}
  {screen==="profile"?<View style={s.center}><Text style={s.title}>NOVA Profile</Text><Text style={s.muted}>{session.user.email}</Text><Pressable onPress={()=>supabase?.auth.signOut()} style={s.primary}><Text style={s.dark}>Log out</Text></Pressable></View>:screen==="live"?<View style={s.center}><Ionicons name="radio" size={60} color="#fff"/><Text style={s.title}>NOVA LIVE</Text><Text style={s.muted}>Real streaming is the next integration phase.</Text></View>:<FlatList data={data} keyExtractor={p=>String(p.id)} contentContainerStyle={{padding:12,paddingBottom:90}} renderItem={({item})=><Post p={item} liked={!!liked[item.id]} like={()=>like(item)}/>}/>}
  <View style={s.nav}><Nav i="home" t="Home" on={()=>setScreen("home")}/><Nav i="search" t="Search" on={()=>setScreen("search")}/><Nav i="add-circle" t="Create" on={()=>setScreen("create")}/><Nav i="radio" t="LIVE" on={()=>setScreen("live")}/><Nav i="person" t="Profile" on={()=>setScreen("profile")}/></View>
 </SafeAreaView>
}
function Auth({email,setEmail,password,setPassword,mode,setMode,submit}){return <SafeAreaView style={s.root}><View style={s.auth}><Text style={s.hero}>NOVA</Text><Text style={s.muted}>A new world for communication</Text><TextInput autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} placeholder="Email" placeholderTextColor="#777" style={s.input}/><TextInput secureTextEntry value={password} onChangeText={setPassword} placeholder="Password" placeholderTextColor="#777" style={s.input}/><Pressable onPress={submit} style={s.primary}><Text style={s.dark}>{mode==="login"?"Log in":"Create account"}</Text></Pressable><Pressable onPress={()=>setMode(mode==="login"?"signup":"login")}><Text style={s.link}>{mode==="login"?"Create a new account":"I already have an account"}</Text></Pressable></View></SafeAreaView>}
function Post({p,liked,like}){return <View style={s.card}><Text style={s.user}>{p.username||"NOVA"}</Text><Text style={s.post}>{p.text}</Text><View style={s.row}><Pressable onPress={like}><Ionicons name={liked?"heart":"heart-outline"} size={23} color="#fff"/></Pressable><Text style={s.muted}>{(p.likes||0)+(liked?1:0)} likes</Text><Ionicons name="chatbubble-outline" size={21} color="#fff"/><Text style={s.muted}>{p.comments||0}</Text><Ionicons name="share-social-outline" size={21} color="#fff"/></View></View>}
function Nav({i,t,on}){return <Pressable onPress={on} style={s.navItem}><Ionicons name={i} size={22} color="#fff"/><Text style={s.muted}>{t}</Text></Pressable>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#09090b"},header:{height:58,flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:18,borderBottomWidth:1,borderBottomColor:"#222"},logo:{color:"#fff",fontSize:27,fontWeight:"900",letterSpacing:2},auth:{flex:1,justifyContent:"center",padding:24},hero:{color:"#fff",fontSize:56,fontWeight:"900",textAlign:"center",marginBottom:6},muted:{color:"#777",fontSize:12},input:{backgroundColor:"#15151a",color:"#fff",borderWidth:1,borderColor:"#292930",borderRadius:12,padding:14,margin:12},big:{minHeight:130,backgroundColor:"#15151a",color:"#fff",padding:14,borderRadius:12,textAlignVertical:"top"},pad:{padding:14},title:{color:"#fff",fontSize:22,fontWeight:"800",marginBottom:12},row:{flexDirection:"row",alignItems:"center",gap:12,marginTop:12},btn:{borderWidth:1,borderColor:"#333",padding:12,borderRadius:10},bt:{color:"#fff",fontWeight:"700"},primary:{backgroundColor:"#fff",padding:14,borderRadius:12,alignItems:"center",marginTop:10},dark:{color:"#09090b",fontWeight:"800"},link:{color:"#fff",textAlign:"center",marginTop:18},card:{backgroundColor:"#111116",borderRadius:16,padding:14,marginBottom:12,borderWidth:1,borderColor:"#202027"},user:{color:"#fff",fontWeight:"800"},post:{color:"#eee",fontSize:16,lineHeight:23,marginTop:12},center:{flex:1,alignItems:"center",justifyContent:"center",padding:25},nav:{position:"absolute",bottom:0,left:0,right:0,height:70,backgroundColor:"#0e0e12",borderTopWidth:1,borderTopColor:"#222",flexDirection:"row",justifyContent:"space-around",alignItems:"center"},navItem:{alignItems:"center",gap:3}});
